### ISSUE TITLE
bug: Unexpected end of JSON input

### ISSUE THREAD

**Issue by mosaic101** [wisnuc/wisnuc-drop#14]
```bash
SyntaxError
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at PartStream.part.on (/home/ubuntu/data/source/src/services/storeFile.js:139:27)
at emitOne (events.js:115:13)
at PartStream.emit (events.js:210:7)
at PartStream.Readable.read (_stream_readable.js:478:10)
at flow (_stream_readable.js:849:34)
at resume_ (_stream_readable.js:831:3)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by mosaic101** [comment]
fix
